name: Train Model Component
description: A component to train the Iris classification model.
inputs:
- name: bucket_name
  type: String
implementation:
  container:
    image: us-central1-docker.pkg.dev/test-mlops-pipeline-438622/my-docker-repo/iris-train:latest
    command:
    - python
    - /app/train.py
    - --bucket_name
    - {inputValue: bucket_name}
